from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdateModelPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, update_id=None):  # noqa: E501
        """UpdateModelPost200Response - a model defined in OpenAPI

        :param update_id: The update_id of this UpdateModelPost200Response.  # noqa: E501
        :type update_id: str
        """
        self.openapi_types = {
            'update_id': str
        }

        self.attribute_map = {
            'update_id': 'update_id'
        }

        self._update_id = update_id

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateModelPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _update_model_post_200_response of this UpdateModelPost200Response.  # noqa: E501
        :rtype: UpdateModelPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def update_id(self) -> str:
        """Gets the update_id of this UpdateModelPost200Response.

        The SHA256 hash of the uploaded weights.  # noqa: E501

        :return: The update_id of this UpdateModelPost200Response.
        :rtype: str
        """
        return self._update_id

    @update_id.setter
    def update_id(self, update_id: str):
        """Sets the update_id of this UpdateModelPost200Response.

        The SHA256 hash of the uploaded weights.  # noqa: E501

        :param update_id: The update_id of this UpdateModelPost200Response.
        :type update_id: str
        """

        self._update_id = update_id
