from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ValidateGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, model_id=None, update_id=None):  # noqa: E501
        """ValidateGet200Response - a model defined in OpenAPI

        :param model_id: The model_id of this ValidateGet200Response.  # noqa: E501
        :type model_id: str
        :param update_id: The update_id of this ValidateGet200Response.  # noqa: E501
        :type update_id: str
        """
        self.openapi_types = {
            'model_id': str,
            'update_id': str
        }

        self.attribute_map = {
            'model_id': 'model_id',
            'update_id': 'update_id'
        }

        self._model_id = model_id
        self._update_id = update_id

    @classmethod
    def from_dict(cls, dikt) -> 'ValidateGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _validate_get_200_response of this ValidateGet200Response.  # noqa: E501
        :rtype: ValidateGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_id(self) -> str:
        """Gets the model_id of this ValidateGet200Response.

        The model ID.  # noqa: E501

        :return: The model_id of this ValidateGet200Response.
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id: str):
        """Sets the model_id of this ValidateGet200Response.

        The model ID.  # noqa: E501

        :param model_id: The model_id of this ValidateGet200Response.
        :type model_id: str
        """

        self._model_id = model_id

    @property
    def update_id(self) -> str:
        """Gets the update_id of this ValidateGet200Response.

        The update ID (SHA256 hash).  # noqa: E501

        :return: The update_id of this ValidateGet200Response.
        :rtype: str
        """
        return self._update_id

    @update_id.setter
    def update_id(self, update_id: str):
        """Sets the update_id of this ValidateGet200Response.

        The update ID (SHA256 hash).  # noqa: E501

        :param update_id: The update_id of this ValidateGet200Response.
        :type update_id: str
        """

        self._update_id = update_id
