from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ValidateModelGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, model=None, weights=None, error=None):  # noqa: E501
        """ValidateModelGet200Response - a model defined in OpenAPI

        :param model: The model of this ValidateModelGet200Response.  # noqa: E501
        :type model: str
        :param weights: The weights of this ValidateModelGet200Response.  # noqa: E501
        :type weights: str
        :param error: The error of this ValidateModelGet200Response.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'model': str,
            'weights': str,
            'error': str
        }

        self.attribute_map = {
            'model': 'model',
            'weights': 'weights',
            'error': 'error'
        }

        self._model = model
        self._weights = weights
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ValidateModelGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _validate_model_get_200_response of this ValidateModelGet200Response.  # noqa: E501
        :rtype: ValidateModelGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model(self) -> str:
        """Gets the model of this ValidateModelGet200Response.


        :return: The model of this ValidateModelGet200Response.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model: str):
        """Sets the model of this ValidateModelGet200Response.


        :param model: The model of this ValidateModelGet200Response.
        :type model: str
        """

        self._model = model

    @property
    def weights(self) -> str:
        """Gets the weights of this ValidateModelGet200Response.


        :return: The weights of this ValidateModelGet200Response.
        :rtype: str
        """
        return self._weights

    @weights.setter
    def weights(self, weights: str):
        """Sets the weights of this ValidateModelGet200Response.


        :param weights: The weights of this ValidateModelGet200Response.
        :type weights: str
        """

        self._weights = weights

    @property
    def error(self) -> str:
        """Gets the error of this ValidateModelGet200Response.


        :return: The error of this ValidateModelGet200Response.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this ValidateModelGet200Response.


        :param error: The error of this ValidateModelGet200Response.
        :type error: str
        """

        self._error = error
