openapi: 3.0.0
info:
  description: API for validating a model with provided weights
  title: Model Validation API
  version: 1.0.0
servers:
- url: /
paths:
  /validate_model:
    post:
      operationId: validate_model_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_validate_model_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_validate_model_post_200_response'
          description: Validation result
      summary: Validate the model with provided weights
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    _validate_model_post_200_response:
      example:
        model: model
        weights: weights
        error: error
      properties:
        model:
          title: model
          type: string
        weights:
          format: base64
          title: weights
          type: string
        error:
          nullable: true
          title: error
          type: string
      title: _validate_model_post_200_response
      type: object
    _validate_model_post_request:
      properties:
        model:
          description: The model architecture
          enum:
          - cifar10
          title: model
          type: string
        weights:
          description: The model weights as a base64 encoded string
          format: base64
          title: weights
          type: string
      required:
      - model
      - weights
      title: _validate_model_post_request
      type: object
