openapi: 3.0.0
info:
  description: API for validating a model with provided weights
  title: Model Validation API
  version: 1.0.0
servers:
- url: /
paths:
  /validate_model:
    get:
      operationId: validate_model_get
      parameters:
      - description: The model architecture
        explode: true
        in: query
        name: model
        required: true
        schema:
          enum:
          - cifar10
          type: string
        style: form
      - description: "The model weights (to overcome the limitation of GET request,\
          \ this field will receive a file path for now)"
        explode: true
        in: query
        name: weights
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_validate_model_get_200_response'
          description: Validation result
      summary: Validate the model with provided weights
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    _validate_model_get_200_response:
      example:
        model: model
        weights: weights
        error: error
      properties:
        model:
          title: model
          type: string
        weights:
          format: base64
          title: weights
          type: string
        error:
          nullable: true
          title: error
          type: string
      title: _validate_model_get_200_response
      type: object
